const homeItems = [
  {
    id: 1,
    nameUser: "Lian Oneill",
    user: "@LianOneill",
    hour: "1h",
    tuit: "is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry, is simply dummy is is simply dummy text of the printing and typesetting industry.",
    avatar: require("../../assets/img/useruno.jpg"),
    image: require("../../assets/img/code.jpg"),
    // textAction: "Nombre del usuario indicó que le gusta",
    // iconAction: "cards-heart",
    iconVertical: "dots-vertical",
    iconBottom: [
      {
        id: 1,
        iconName: "chat-outline",
      },
      {
        id: 2,
        iconName: "repeat",
      },
      {
        id: 3,
        iconName: "heart-outline",
      },
      {
        id: 4,
        iconName: "share-variant",
      },
    ],
    iterations: 367,
    retuit: 1.256,
    like: 2.004,
    tuitCited: 2,
    hourMinute: "12:07",
    date: "06 jun. 21",
    device: "Twitter for iPhone",
  },
  {
    id: 2,
    nameUser: "Anaiah Whitten",
    user: "@AnaiahWhitten",
    hour: "3h",
    tuit: "is simply dummy text of the printing and typesetting industry 😍  ",
    avatar: require("../../assets/img/userdos.jpg"),
    image: require("../../assets/img/road.jpg"),
    textAction: "Aliah Pitts retwitteó",
    iconAction: "repeat",
    iconVertical: "dots-vertical",
    iconBottom: [
      {
        id: 1,
        iconName: "chat-outline",
      },
      {
        id: 2,
        iconName: "repeat",
      },
      {
        id: 3,
        iconName: "heart-outline",
      },
      {
        id: 4,
        iconName: "share-variant",
      },
    ],
    iterations: 67,
    retuit: 1.962,
    like: 10.004,
    tuitCited: 25,
    hourMinute: "16:07",
    date: "06 jun. 21",
    device: "Twitter Web App",
  },
  {
    id: 3,
    nameUser: "Ian Dejesus",
    user: "@Ian_Dejesus",
    hour: "1h",
    tuit: "is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry, is simply dummy is simply dummy text of the printing and typesetting industry.  ",
    avatar: require("../../assets/img/usertres.jpg"),
    image: require("../../assets/img/reactnative.jpg"),
    textAction: "Emeline Duarte indicó que le gusta",
    iconAction: "cards-heart",
    iconVertical: "dots-vertical",
    iconBottom: [
      {
        id: 1,
        iconName: "chat-outline",
      },
      {
        id: 2,
        iconName: "repeat",
      },
      {
        id: 3,
        iconName: "heart-outline",
      },
      {
        id: 4,
        iconName: "share-variant",
      },
    ],
    iterations: 25,
    retuit: 125,
    like: 52,
    tuitCited: 5,
    hourMinute: "17:47",
    date: "05 jun. 21",
    device: "Twitter for Android",
  },
  {
    id: 4,
    nameUser: "Aada Laine",
    user: "@AadaLaine_",
    hour: "5h",
    tuit: "is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry, is simply dummy is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry, is simply dummy is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry, is simply dummy ",
    avatar: require("../../assets/img/usercuatro.jpg"),
    //image: require("../../assets/img/partido.jpg"),
    textAction: "Dylan Ambrose indicó que le gusta",
    iconAction: "cards-heart",
    iconVertical: "dots-vertical",
    iconBottom: [
      {
        id: 1,
        iconName: "chat-outline",
      },
      {
        id: 2,
        iconName: "repeat",
      },
      {
        id: 3,
        iconName: "heart-outline",
      },
      {
        id: 4,
        iconName: "share-variant",
      },
    ],
    iterations: 3,
    retuit: 1,
    like: "",
    tuitCited: 1,
    hourMinute: "12:07",
    date: "06 jun. 21",
    device: "Twitter for iPhone",
  },
  {
    id: 5,
    nameUser: "Jakoby Roman",
    user: "@Jakoby19",
    hour: "2h",
    tuit: "is simply dummy text of the printing and typesetting  ",
    avatar: require("../../assets/img/usercinco.jpg"),
    image: require("../../assets/img/city.jpg"),
    // textAction: "Nombre del usuario retwitteó",
    // iconAction: "repeat",
    iconVertical: "dots-vertical",
    iconBottom: [
      {
        id: 1,
        iconName: "chat-outline",
      },
      {
        id: 2,
        iconName: "repeat",
      },
      {
        id: 3,
        iconName: "heart-outline",
      },
      {
        id: 4,
        iconName: "share-variant",
      },
    ],
    iterations: "",
    retuit: 12,
    like: 5,
    tuitCited: 2,
    hourMinute: "09:07",
    date: "05 jun. 21",
    device: "Twitter for Android",
  },
  {
    id: 6,
    nameUser: "Oaklee Odom",
    user: "@OakleeOdom",
    hour: "2h",
    tuit: "is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry, is simply dummy is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry, is simply dummy is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry, is simply dummy ",
    avatar: require("../../assets/img/userseis.jpg"),
    //image: require("../../assets/img/partido.jpg"),
    // textAction: "Nombre del usuario retwitteó",
    // iconAction: "repeat",
    iconVertical: "dots-vertical",
    iconBottom: [
      {
        id: 1,
        iconName: "chat-outline",
      },
      {
        id: 2,
        iconName: "repeat",
      },
      {
        id: 3,
        iconName: "heart-outline",
      },
      {
        id: 4,
        iconName: "share-variant",
      },
    ],
    iterations: 69,
    retuit: 856,
    like: 357,
    tuitCited: 8,
    hourMinute: "20:07",
    date: "05 jun. 21",
    device: "Twitter Web App",
  },
];

export default homeItems;
